config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :books do
    resources :products, except: %i[ index ] do
      resources :messages, except: %i[ index ]
    end
  end
  get '/products/', to: 'products#index'
  get '/messages/', to: 'messages#index'
  get '/dashboard/', to: 'homes#dashboard'
  get '/message/:user_id/book/:book_id', to: 'messages#book_messages', as: 'book_messages'

  devise_for :users

  root 'homes#index'
end

app/views/shared/_navbar.html.erb
<div class='bg-dark'>
    <nav class="navbar navbar-expand-lg navbar-white bg-dark row mx-md-4">
        <div class="col col-3">
            <a class="navbar-brand text-white text-decoration-none" href="<%= root_path %>">Books on Rails</a>
        </div>
        <div class="col col-6 text-center m-auto">
            <%= form_tag dashboard_path, method: :get do %>
                <div class="form-group">
                    <%= text_field_tag :text, params[:text], placeholder: "Buscar" %>
                </div>
                <%= submit_tag "Buscar", name: nil%>
            <% end %>
        </div>
        <div class="col col-3 text-white d-flex justify-content-end">
            <h6 class='my-auto d-none d-lg-block'><%= current_user.first_name + " " + current_user.last_name if user_signed_in? %></h6>
            <div class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-toggle="dropdown" aria-expanded="false">Usuario</a>
                <div class="dropdown-menu">
                    <% if user_signed_in? %>
                        <h6 class='dropdown-item text-dark d-lg-none'><%= current_user.first_name + " " + current_user.last_name %></h6> 
                        <h6 class='dropdown-item text-dark'><%= link_to 'Mensajes', messages_path, class:'text-decoration-none' %></h6>
                        <h6 class='dropdown-item text-dark'><%= link_to 'Mis Publicaciones', products_path, class:'text-decoration-none' %></h6>
                        <div class="dropdown-divider"></div>
                            <h6 class='dropdown-item text-dark'><%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete, class:'text-decoration-none' %></h6>
                       </div>
                    <% else %>
                        <h6 class='dropdown-item text-dark'><%= link_to 'Registrarse', new_user_registration_path, class:'text-decoration-none' %></h6>
                        <h6 class='dropdown-item text-dark'><%= link_to 'Iniciar sesión', new_user_session_path, class:'text-decoration-none' %></h6>
                    <% end %>
                </div>
            </div>
        </div>
    </nav>
</div>