config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :books do
    resources :products, except: %i[ index ] do
      resources :messages, except: %i[ index ]
    end
  end
  get '/products/', to: 'products#index'
  get '/messages/', to: 'messages#index'
  get '/dashboard/', to: 'homes#dashboard'
  get '/message/:user_id/book/:book_id', to: 'messages#book_messages', as: 'book_messages'

  devise_for :users

  root 'homes#index'
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :messages
    has_one_attached :image
    
    enum category: [ :"Lectura complementaria", :"Texto de estudio" ]
    enum course: [ :"1° básico", :"2° básico", :"3° básico", :"4° básico", :"5° básico", :"6° básico", :"7° básico", :"8° básico", :"I Medio", :"II Medio", :"III Medio", :"IV Medio" ]

    scope :from_course, ->(id) { where course: id }

    paginates_per 12
    def dom
        self.where(category: 0)
    end

    def text
        self.where(category: 1)
    end
    
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]
  before_action :set_course, only: %i[ index show new edit]
  before_action :set_category, only: %i[ new edit]
  before_action :set_products, only: %i[ show]
  before_action :authenticate_user!, only: %i[ new create edit updated destroy]


  # GET /books or /books.json
  def index
    if (params[:curso])
      @doms = Book.with_attached_image.from_course(params[:curso]).where(category: 0).page(params[:page])
      @texts = Book.with_attached_image.from_course(params[:curso]).all.where(category:1 ).page(params[:page])
    else
      @doms = []
      @texts = []
    end
  end

  # GET /books/1 or /books/1.json
  def show

  end

  # GET /books/new
  def new
    if current_user.admin?
      @book = Book.new 
    else
      redirect_to root_path
    end
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    def set_course
      @course = Book.courses.keys.map {|course| [course, course] }
    end

    def set_category
      @category = Book.categories.keys.map {|category| [category, category] }
    end

    def set_products
      @products = Product.where(book: @book)
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :author, :editorial, :course, :category, :image)
    end
    
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<form>
  <div class="field form-group">
    <%= form.label "Título", class:'mb-0' %>
    <%= form.text_field :title, class:"form-control mt-0" %>
  </div>

  <div class="field form-group">
    <%= form.label "Autor" %>
    <%= form.text_field :author, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label "Editorial" %>
    <%= form.text_field :editorial, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label "Curso"%>
    <%= form.select :course, @course%>
  </div>

  <div class="form-group">
    <%= form.label "Categoría" %>
    <%= form.select  :category, @category%>
  </div>

  <div class="form-group">
    <%= form.label "Imagen referencial" %>
    <%= form.file_field :image%>
  </div>

  <div class="actions">
    <%= form.submit "Guardar", class:"btn btn-dark text-white btn-block" %>
  </div>

</form>

<% end %>

app/views/books/edit.html.erb
<div class="container col-md-6">
    <h2>Editar Libro</h2>
    <%= render 'form', book: @book %>
</div>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<div class="album py-5 bg-light">
  <div class="container">
    <div class= 'text-right h6'>
      <%= link_to 'Volver a todos los cursos', root_path, class:'text-decoration-none' %> <br>
      <%= link_to 'Agregar libro', new_book_path, class:'text-decoration-none' if current_user.admin? %>
    </div>
    <h1><%= @doms.last.course %></h1><br>
    <h2>Lectura domiciliaria</h3>
    <div class="row">
      <% @doms.each do |book| %>
        <div class="col-md-3">
          <div class="card mb-4 shadow-sm text-center">
            <%= image_tag book.image.variant(resize: '100x150').processed %>
            <div class="card-body">
              <h5 class="card-text"><%= book.title%></h5>
              <h5 class="card-text"><%= book.author%></h5>
              <p class="card-text"><%= book.editorial%></p>
              <%= link_to 'Ver publicaciones', book_path(book), class: 'btn btn-warning btn-block text-decoration-none text-primary' %><br>
              <%= link_to 'Publicar', new_book_product_path(book), class: 'btn btn-primary btn-block text-decoration-none text-warning' %>
             </div>
            <div>
              <% if current_user.admin? %>
                <%= link_to 'Editar', edit_book_path(book), class: 'text-decoration-none text-dark' %>  |
                <%= link_to 'Eliminar', book_path(book), method: :delete, data: { confirm: '¿Estás seguro de querer eliminar este registro?' }, class: 'text-decoration-none text-dark'  %>       
              <% end %>                     
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <br>
  <br>
  <div class="container">
        <h2>Textos de Estudio</h3>
    <div class="row">
      <% @texts.each do |book| %>
        <div class="col-md-3">
          <div class="card mb-4 shadow-sm text-center">
            <%= image_tag book.image.variant(resize: '100x150').processed %>
            <div class="card-body">
              <h5 class="card-text"><%= book.title%></h5>
              <h5 class="card-text"><%= book.author%></h5>
              <p class="card-text"><%= book.editorial%></p>
              <%= link_to 'Ver publicaciones', book_path(book), class: 'btn btn-warning btn-block text-decoration-none text-primary' %><br>
              <%= link_to 'Publicar', new_book_product_path(book), class: 'btn btn-primary btn-block text-decoration-none text-warning' %>
            </div>
            <div>
              <% if current_user.admin? %>
                <%= link_to 'Editar', edit_book_path(book), class: 'text-decoration-none text-dark' %>  |
                <%= link_to 'Eliminar', book_path(book), method: :delete, data: { confirm: '¿Estás seguro de querer eliminar este registro?' }, class: 'text-decoration-none text-dark'  %>       
              <% end %>                     
            </div>
          </div>
        </div>
      <% end %>
      </div>
  </div>
</div>

app/views/books/new.html.erb
<div class="container col-md-6">
    <h2>Agregar Libro</h2>
    <%= render 'form', book: @book %>
</div>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<div class="album py-5 bg-light">
  <div class="container">
    <div class= 'd-flex justify-content-end h5' >
      <%= link_to "Volver a #{@book.course}", books_path(curso: @book.course ), class:'text-decoration-none'%>
    </div>
    <h2><%= @book.title %></h3>
    <h4><%= @book.author %></h4>
    <div class="row">
      <% @products.each do |product| %>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm text-center">
            
            <div id="carouselExampleControlsNoTouching" class="carousel slide" data-touch="false" data-interval="false">
                <div class="carousel-inner">
                  <% product.images.each_with_index do |image, index| %>
                    <% class_values = (index == 0) ? 'carousel-item active' : 'carousel-item' %>
                    <div class='<%= class_values %>'>
                      <%= image_tag image.variant(resize: '500 x 300').processed %>
                    </div>
                  <% end %>
                </div>
                <button class="carousel-control-prev" type="button" data-target="#carouselExampleControlsNoTouching" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-target="#carouselExampleControlsNoTouching" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </button>
            </div>            
            <div class="card-body">
              <h5 class="card-text"><%= product.editorial %></h5>
              <h5 class="card-text">$<%= product.price.to_s.reverse.scan(/.{1,3}/).join('.').reverse %></h5>
              <p class="card-text"><%= product.condition.humanize %></p>
              <p class="card-text"><%= product.status.humanize %></p>
              <%= link_to 'Contactar', new_book_product_message_path(product.book.id, product.id), class: 'btn btn-success btn-block text-white text-decoration-none' %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div> 