config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :books do
    resources :products, except: %i[ index ] do
      resources :messages, except: %i[ index ]
    end
  end
  get '/products/', to: 'products#index'
  get '/messages/', to: 'messages#index'
  get '/dashboard/', to: 'homes#dashboard'
  get '/message/:user_id/book/:book_id', to: 'messages#book_messages', as: 'book_messages'

  devise_for :users

  root 'homes#index'
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :book
  has_many_attached :images

  enum condition: [ :aceptable, :bueno, :muy_bueno, :como_nuevo, :nuevo ]
  enum status: [ :disponible, :comprometido]

  def mine
    self.where(user_id: @current_user.id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_book, only: %i[ new edit update create ]
  before_action :set_product, only: %i[ show edit update destroy ]
  before_action :set_condition, only: %i[ new create edit update ]
  before_action :set_status, only: %i[ new create edit update ]
  before_action :authenticate_user!

  def index
    @my_products = Product.all.where(user: current_user)
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params.merge(user: current_user))
    @product.book = @book

    respond_to do |format|
      if @product.save
        format.html { redirect_to book_path(@book), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to products_url, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:book_id])
  end    
    
  def set_product
    @product = Product.find(params[:id])
  end

  def set_condition
    @condition = Product.conditions.keys.map{|condition| [condition.humanize, condition] }
  end

  def set_status
    @status = Product.statuses.keys.map{|status| [status.humanize, status] }
  end

  # Only allow a list of trusted parameters through.

  def product_params
    params.require(:product).permit(:editorial,  :price, :condition, :status, images: [])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: [@book, product], local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<h3><%= @book.title %></h5>
<h4><%= @book.author %></h5>
<form>
  <div class="field form-group">
    <%= form.label "Editorial" %>
    <%= form.text_field :editorial, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label "Precio" %>
    <%= form.number_field :price, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label "Condición" %>
    <%= form.select :condition, @condition%>
  </div>

  <div class="form-group">
    <%= form.label "Estado"%>
    <%= form.select :status, @status%>
  </div>

  <div class="form-group">
    <%= form.label "Imagen referencial" %>
    <%= form.file_field :images, multiple: true%>
  </div>

  <div class="actions">
    <%= form.submit "Guardar", class:"btn btn-dark text-white btn-block" %>
  </div>

</form>

<% end %>

app/views/products/edit.html.erb
<h1>Editar</h1>

<%= render 'form', product: @product %>

app/views/products/index.html.erb
<div class="container-md mt-3 d-flex justify-content-center">
  <table class="table col-md-8">
    <tbody>
      <% @my_products.each do |product| %>
        <tr class="row border-bottom-dark border-top-dark">
          <td class="d-inline col-8 d-flex justify-content-center">
            <% product.images.each do |image| %>
              <%= image_tag image.variant(resize: '200x200').processed %>
            <% end %>
          </td> 
          <td class="col-4 d-flex align-content-between flex-wrap">
            <div>
              <h4 class="card-text"><%= product.book.title %></h4>
              <h5 class="card-text"><%= product.book.author %></h5>
              <h5 class="card-text"><%= product.editorial %></h5>
              <h6 class="card-text">$<%= product.price.to_s.reverse.scan(/.{1,3}/).join('.').reverse %></h6>
              <h6 class="card-text"><%= product.condition.humanize %></h6>
              <h6 class="card-text"><%= product.status.humanize %></h6>
            </div>
            <div>
              <%= link_to 'Editar', edit_book_product_path(product.book, product), class: 'text-decoration-none text-dark' %> | 
              <%= link_to 'Eliminar', book_product_path(product.book.id, product), method: :delete, data: { confirm: '¿Estás seguro de querer eliminar este registro?' }, class: 'text-decoration-none text-dark' %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/products/new.html.erb
<div class="container col-md-6">
    <h1>Publicar libro</h1>
    <%= render 'form', product: @product %>
</div>
 

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Editorial:</strong>
  <%= @product.editorial %>
</p>

<p>
  <strong>Condition:</strong>
  <%= @product.condition %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Status:</strong>
  <%= @product.status %>
</p>

<p>
  <strong>User:</strong>
  <%= @product.user_id %>
</p>

<p>
  <strong>Book:</strong>
  <%= @product.book_id %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>